const queries = [
	{ name: 'Dashboard', path: '/' },
	{ name: 'Sorting', path: 'sorting' },
	{ name: 'Searching', path: 'searching' },
	{ name: 'Data Structures', path: 'datastructures' },
	{ name: 'Graphs', path: 'graphs' },
	{ name: 'Trees', path: 'trees' },
	{ name: 'Backtracking', path: 'backtracking' },
	{ name: 'Divide and Conquer', path: 'divideconquer' },
	{ name: 'Bubble Sort', path: 'bubblesort' },
	{ name: 'Selection Sort', path: 'selectionsort' },
	{ name: 'Insertion Sort', path: 'insertionsort' },
	{ name: 'Quick Sort', path: 'quicksort' },
	{ name: 'Merge Sort', path: 'mergesort' },
	{ name: 'Arrays', path: 'arrays' },
	{ name: 'Linked List', path: 'linkedlist' },
	{ name: "Dijkstra's", path: 'dijkstras' },
	{ name: 'Bellman Ford', path: 'bellmanford' },
	{ name: 'Breadth First Search', path: 'breadthfirstsearch' },
	{ name: 'Depth First Search', path: 'depthfirstsearch' },
	{ name: "Prim's", path: 'prims' },
	{ name: 'AVL', path: 'avl' },
	{ name: 'Binary Tree', path: 'binaryttree' },
	{ name: 'Preorder', path: 'preorder' },
	{ name: 'Inorder', path: 'inorder' },
	{ name: 'Postorder', path: 'postorder' },
	{ name: 'nQueens', path: 'nqueens' },
];

export default queries;
